name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
        version: 1.52.0
      if: success()
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: test
      run: |
        sudo sed -i '1s/^/nameserver 100.81.143.116\n/' /etc/resolv.conf
        ping -c 4 sonarqube.rounded.space
